let radio1 = document.getElementById("slide1");
let radio2 = document.getElementById("slide2");
let radio3 = document.getElementById("slide3");
let namePl = document.getElementById("planetNameId");
let infoPl = document.getElementById("infoPlId");
radio1.addEventListener("click",openPl);
radio2.addEventListener("click",openPl2);
radio3.addEventListener("click",openPl3);

function openPl(){
    namePl.innerHTML = "MILLER";
    infoPl.innerHTML = "DESPITE THE FACT THAT DUE TO ITS PROXIMITY TO THE BLACK HOLE, THE TIME ON ITS SURFACE IS SLOWED DOWN MANY TIMES: ONE HOUR IS EQUAL TO SEVEN YEARS ON EARTH. THE SHUTTLE 'RANGER' SPLASHES DOWN WHERE THE SIGNALS FROM THE MILLER EXPEDITION CAME FROM, AND EVEN FINDS THE WRECKAGE OF THE SHIP, WHICH HAS NOT YET HAD TIME TO BE SCATTERED BY THE WAVES AFTER THE CRASH THAT HAPPENED A FEW MINUTES AGO LOCAL TIME";
}

function openPl2(){
    namePl.innerHTML = "MANN";
    infoPl.innerHTML = "THE ATMOSPHERE CONTAINS OXYGEN, CHLORINE AND AMMONIA. ON SOLID ICY CLOUDS, THE ASTRONAUTS FIND THE STATION AND DR. MANN SLEEPING IN SUSPENDED ANIMATION. AFTER WAKING UP, THE DELIGHTED DOCTOR SAYS THAT THE PLANET IS A GOOD CANDIDATE FOR COLONIZATION, SINCE CHLORINE DISSIPATES ON THE SURFACE AND YOU CAN BREATHE FREELY, THERE IS ALSO ORGANIC MATTER";
}

function openPl3(){
    namePl.innerHTML = "EDMUNDS";
    infoPl.innerHTML = "THE PLANET APPEARS TO BE A VAST BARREN DESERT, BUT ITS ATMOSPHERE IS BREATHABLE AND THE SOIL CAN BE SUITABLE FOR AGRICULTURE. THE ONLY KNOWN MECHANISM BY WHICH THE PLANET CAN MAINTAIN OXYGEN LEVELS SUFFICIENT FOR HUMAN RESPIRATION FOR AN EXTENDED PERIOD OF TIME IS BIOLOGICAL, SO IT IS LIKELY THAT THERE IS LIFE SOMEWHERE ON THE PLANET THAT GENERATES OXYGEN.";
}